<?php declare(strict_types=1);

namespace Database\Seeders;

use Concept\Extensions\DatabaseEloquent\Contracts\SeederInterface;
use Illuminate\Database\Capsule\Manager as CapsuleManager;
use Illuminate\Database\Seeder;

class PageSeeder extends Seeder implements SeederInterface
{
    public function run(): void
    {
        CapsuleManager::schema()->getConnection()->table('pages')->truncate();

        CapsuleManager::schema()->getConnection()->table('pages')->insert(
            [
                [
                    'title'       => 'Home Page',
                    'slug'        => 'home',
                    'description' => 'Welcome to our Concept Framework website.',
                    'content'     => '<h1>Welcome</h1><p>This is the home page content generated by Seeder.</p>',
                    'published'   => true,
                ],
                [
                    'title'       => 'About Us',
                    'slug'        => 'about',
                    'description' => 'Learn more about our philosophy and architecture.',
                    'content'     => '<h1>About Us</h1><p>We build clean and aesthetic PHP applications.</p>',
                    'published'   => true,
                ],
                [
                    'title'       => 'Terms of Service',
                    'slug'        => 'terms',
                    'description' => 'Legal information and usage terms.',
                    'content'     => '<h1>Terms</h1><p>Please be nice to our servers.</p>',
                    'published'   => false,
                ],
            ]
        );
    }
}